services:
#  web-server:
#    container_name: web-server
#    image: nginx
#    ports:
#      - 80:80

  cache-server:
    container_name: redis-server
    image: redis
    ports:
      - 6379:6379

  db-server:
    container_name: db-server
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pwd1234
    volumes:
      - ./mysql_data:/var/lib/mysql